server:
  port: 8080

spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: redis
    port: 6379
  autoconfigure:
    redis:
      enable-keyspace-events: true
  data:
    redis:
      timeout: 2000
      connect-timeout: 2000

jwt:
  key: Nh2z3IBYqvuxat3nWr3i5QUdrXvHp743GAYuXHFiS65vBlfpU05oAPfXT3TxtNbAfFzTZEeHPj8Nu+HPObwnnA==
  access-expiration: 900000
  refresh-expiration: 604800000

app:
  repository: jpa
  cors:
    allowed-origins: http://localhost:3000
